# Use an official Python runtime as a parent image
FROM python:3.12

LABEL maintainer="3mahrukh3@gmail.com"

# Set the working directory in the container
WORKDIR /Backend/microservices-eda/ProductService/

RUN apt-get update && apt-get install -y protobuf-compiler

# Install system dependencies required for potential Python packages
RUN apt-get update && \
    apt-get install -y \
    build-essential \
    libpq-dev \
    protobuf-compiler \
    && rm -rf /var/lib/apt/lists/*

# Install Poetry
RUN pip install poetry

# Copy the current directory contents into the container at /Backend/microservices-eda/ProductService/producer
COPY . .

# Configuration to avoid creating virtual environments inside the Docker container
RUN poetry config virtualenvs.create false

# Install dependencies including development ones
RUN poetry install

# Make port 8000 available to the world outside this container
EXPOSE 8000 

CMD ["uvicorn", "producer.main_producer:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]