# Use an official Python runtime as a parent image
FROM python:3.12

LABEL maintainer="3mahrukh3@gmail.com"

# Set the working directory in the container
WORKDIR /Backend/microservices-eda/ProductService/consumer/

# Install system dependencies required for potential Python packages
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        libpq-dev \
        protobuf-compiler \
    && rm -rf /var/lib/apt/lists/*

# Install Poetry
RUN pip install poetry

# Copy the current directory contents into the container at /Backend/microservices-eda/ProductService/consumer
COPY . .

# Configuration to avoid creating virtual environments inside the Docker container
RUN poetry config virtualenvs.create false

# Install dependencies including development ones
RUN poetry install

# Make port 8001 available to the world outside this container
EXPOSE 8004

# Command to run the application
CMD ["uvicorn", "main_consumer:app", "--host", "0.0.0.0", "--port", "8004", "--reload"]
